
CREATE TABLE IF NOT EXISTS public.doador
(
	codigo bigserial,
    nome text,
    cpf text,
    contato text,
    tipoerhcorretos boolean,
    rh text,
    tiposanguineo text,
    situacao text,
    PRIMARY KEY (codigo)
);

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.doador
(
    codigo bigserial NOT NULL,
    nome text COLLATE pg_catalog."default",
    cpf text COLLATE pg_catalog."default",
    contato text COLLATE pg_catalog."default",
    tipoerhcorretos boolean,
    rh text COLLATE pg_catalog."default",
    tiposanguineo text COLLATE pg_catalog."default",
    situacao text COLLATE pg_catalog."default",
    CONSTRAINT doador_pkey PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.doacao
(
    codigo bigserial NOT NULL,
    data date,
    hora time with time zone,
    volume double precision,
    cod_doador bigint NOT NULL,
    PRIMARY KEY (codigo)
);

ALTER TABLE IF EXISTS public.doacao
    ADD CONSTRAINT codigo_doador FOREIGN KEY (cod_doador)
    REFERENCES public.doador (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;